---
- hosts: trendmicro
  collections:
    - trendmicro.deepsec
  tasks:
    - name: Create Anti Malware config
      trendmicro.deepsec.anti_malware_config:
        name: Demo Malware scan_config
        description: demo scan
        scan_action_for_virus: quarantine
        alert_enabled: true
        scan_type: real-time
        real_time_scan: read-write
        cpu_usage: medium
        state: present
      register: malware_config
    - name: Malware Config
      debug:
        msg: "{{ malware_config }}"
    - name: Create New policy for malware scan config
      trendmicro.deepsec.policies_config:
        name: Demo Malware Policy
        description: TM pol for newly created AntiMalware config
        state: present
        recommendation_scan_mode: ongoing
        anti_malware:
          state: on
          real_time_scan_configuration_id: "{{ malware_config['anti_malware_config']['ID'] }}"
          real_time_scan_schedule_id: 1
      register: policy_config
    - name: Policy Config
      debug:
        msg: "{{ policy_config['policies_config'] }}"